[packages]
ast-grep = "0.38.5"
bacon = "3.14.0"
bat = "0.25.0"
cargo-binstall = "1.14.1"
cargo-bundle = "0.7.0"
cargo-generate = "0.23.3"
cargo-info = "0.7.7"
coreutils = "0.0.30"
dioxus-cli = "0.6.3"
du-dust = "1.2.0"
dua = "1.1.0"
embargo = "0.1.0"
evcxr_jupyter = "0.20.0"
exa = "0.10.1"
fd-find = "10.2.0"
flamegraph = "0.6.8"
fselect = "0.8.12"
gh = "0.1.0"
git-delta = "0.18.2"
gitui = "0.27.0"
hyfetch = "0.1.0"
hyperfine = "1.19.0"
irust = "1.73.0"
just = "1.40.0"
leptosfmt = "0.1.33"
mprocs = "0.7.3"
nu = "0.105.1"
porsmo = "0.3.3"
presenterm = "0.14.0"
rbonsai = "0.1.5"
ripgrep = "14.1.1"
ripgrep_all = "0.10.9"
rusty-man = "0.5.0"
rusty-rain = "0.3.7"
sccache = "0.10.0"
sendme = "0.26.0"
speedtest-rs = "0.2.0"
starship = "1.23.0"
tauri-cli = "2.5.0"
terminal-arcade = "0.0.1"
tlrc = "1.11.1"
tokei = "12.1.2"
trunk = "0.21.14"
wasm-bindgen-cli = "0.2.100"
wiki-tui = "0.9.1"
xh = "0.24.1"
yazi-cli = "25.5.31"
yazi-fm = "25.5.31"
zellij = "0.42.2"
zoxide = "0.9.8"
