[[session]]
name = "dot"
path = "~/dotfiles"

[[session]]
name = "explore"
path = "~/dev/explore"

[[session]]
name = "time"
path = "~/"
startup_command = "tmux clock-mode"

[[session]]
name = "iamb"
path = "~/"
startup_command = "iamb"

[[session]]
name = "nethack"
path = "~/"
startup_command = "nethack"
preview_command = "figlet nethack\n@"
# preview_command = ''' bash -c 'eval " figlet nethack; figlet -f colossal @ " ' '''

[default_session]
preview_command = "eza --all --git --icons --color=always {}"
