{pkgs, ...}: {
  home.packages = with pkgs;
    [
      (firefox_decrypt.override {nss = nss_latest;})
      asciiquarium
      bat
      bat-extras.batman
      btop
      cmatrix
      dbus
      delta
      dict
      dua
      eza
      fd
      ffmpeg
      fontconfig
      fzf
      ghostscript
      glow
      gnupg
      iamb
      imagemagick
      just
      mediainfo
      mermaid-cli
      ncspot
      neofetch
      nushell
      p7zip
      pass
      presenterm
      ripgrep
      rustmission
      sesh
      skim
      starship
      syncthing
      timewarrior
      timg
      tlrc
      tmux
      tokei
      usbutils
      wget
      xclip
      yazi
      yt-dlp
      zathura
      zip
      zoxide
    ]
    ++ lib.optionals (pkgs.stdenv.isLinux) [
      dmenu
      parted
      quickshell
      rofi
      wineWowPackages.stable
    ];
}
