{pkgs, ...}: {
  home.packages = with pkgs;
    [
      (firefox_decrypt.override {nss = nss_latest;})
      asciiquarium
      bat
      bat-extras.batman
      btop
      cmatrix
      dbus
      delta
      dict
      dua
      eza
      fastfetch
      fd
      ffmpeg
      figlet
      fontconfig
      fzf
      ghostscript
      glow
      gnupg
      hyfetch
      iamb
      imagemagick
      just
      macchina
      mediainfo
      mermaid-cli
      mupdf
      ncspot
      nushell
      p7zip
      pass
      pinentry-tty
      presenterm
      ripgrep
      rustmission
      sesh
      skim
      starship
      syncthing
      timewarrior
      timg
      tlrc
      tmux
      tokei
      usbutils
      wget
      xclip
      yazi
      yt-dlp
      zathura
      zip
      zoxide
    ]
    ++ lib.optionals (pkgs.stdenv.isLinux) [
      dmenu
      hygg
      parted
      quickshell
      rofi
      wineWow64Packages.stable
    ];
}
