"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
final_space = true
version = 3

[palette]
os = "#ACB0BE"
pink = "#F5BDE6"
lavender = "#B7BDF8"
blue = "#8AADF4"
wight = "#FFFFFF"
text = "#494D64"

[[blocks]]
type = "prompt"
alignment = "left"

	[[blocks.segments]]
	type = "os"
	style = "diamond"
	background = "p:blue"
	foreground = "p:wight"
	leading_diamond = "\ue0b6"
	trailing_diamond = "\ue0b4"
	template = "{{.Icon}} "

	[[blocks.segments]]
	type = "session"
	style = "diamond"
	background = "p:blue"
	foreground = "p:text"

	[[blocks.segments]]
	type = "path"
	style = "powerline"
	powerline_symbol = "\ue0b4"
	background = "p:pink"
	foreground = "p:text"
	template = " {{ .Path }}"

		[blocks.segments.properties]
	   folder_icon = "..\ue5fe.."
	   style = "agnoster_short"

	[[blocks.segments]]
	type = "git"
	style = "powerline"
	powerline_symbol = "\ue0b4"
	template = " {{ .HEAD }}"
	background = "p:lavender"
	foreground = "p:text"

		[properties]
		branch_icon = "\ue725 "
		cherry_pick_icon = "\ue29b "
		commit_icon = "\uf417 "
		fetch_status = false
		fetch_upstream_icon = false
		merge_icon = "\ue727 "
		no_commits_icon = "\uf0c3 "
		rebase_icon = "\ue728 "
		revert_icon = "\uf0e2 "
		tag_icon = "\uf412" 
